# Makefile
#
# ARCH=arm CROSS_COMPILE=arm-himix200-linux- make -C /home/a003257/er330/src/osdrv/opensource/kernel/linux-4.9.y-smp M=/home/a003257/ldd/00_hello modules
#
# ARCH=arm CROSS_COMPILE=arm-himix200-linux- make -C /home/a003257/er330/src/osdrv/opensource/kernel/linux-4.9.y-smp M=/home/a003257/ldd/00_hello modules clean

obj-m += hello2.o

EXTRA_CFLAGS += -D__TEST__
